### ISSUE TITLE
Appears to be no way to download or run RVC model

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#10]
I really like what you're doing!😄  But I was trying the new RVC feature and it appears to be no way to run it right now. Nothing shows up at the dropdown menu and nothing auto downloads like the other tts models. Everything else works fine.

**Comment by gitmylo** [comment]
RVC is not based on a single model, every voice has it's own model basically.
to install an RVC model, unzip the zip it comes in, and put it in a subdirectory of `data/models/rvc`

there's some models on [this discord server](https://discord.gg/aihub) and on [this huggingface repo](https://huggingface.co/QuickWick/Music-AI-Voices/tree/main)

**Comment by nekogecko2** [comment]
Thank you for your help! I didn't know you had to put the weights in a new folder within /data/models/rvc. It works now!
