### ISSUE TITLE
No suitable Python runtime found [QUESTION] 

### ISSUE THREAD

**Issue by nookie-dotcom** [gitmylo/audio-webui#101]
# No suitable Python runtime found

W10. I have python installed. Python -V = Python 3.10.12
but when i do run.bat the following error appears:

No suitable Python runtime found
Pass --list (-0) to see all detected environments on your machine
or set environment variable PYLAUNCHER_ALLOW_INSTALL to use winget
or open the Microsoft Store to the requested version.

**Comment by gitmylo** [comment]
What did you use to install python 3.10?
It appears you installed a python 3 version using the official installer, then used the windows store installer for 3.10.

Please use the official python installer from https://www.python.org/ and make sure it adds it to the py launcher (already on by default)

**Comment by nookie-dotcom** [comment]
Thanks for answering. I only used the official installer since i can't use the windows store at all (firewall).

**Comment by gitmylo** [comment]
Can you run `py -0` in a cmd and tell me what it says? It should show all installed versions that were installed with python launcher enabled.

If there's no python 3.10 version showing up at all, reinstall python 3.10, make sure you install it with py launcher support.

**Comment by nookie-dotcom** [comment]
When i do: py -0 the output is  -V:3.11 *        Python 3.11 (64-bit)
and when i do
python -V is shows: Python 3.10.9 (both in Anaconda Prompt, base env).
And Python 3.11.2 in cmd.exe. 

Something's messed up on my side i guess.

**Comment by gitmylo** [comment]
Well, you can edit the bat file to use the python command only, by removing the part where it tries to use py.
Or you could reinstall python 3.10

**Comment by nookie-dotcom** [comment]
thank you so much. the re-install did the trick.

**Comment by gitmylo** [comment]
Great to hear!
