### ISSUE TITLE
[BUG REPORT] LLVM ERROR: Symbol not found: __svml_cosf8_ha

### ISSUE THREAD

**Issue by Sunflex616** [gitmylo/audio-webui#106]
**Description**
After executing the "run.bat" which seems to finish the installation without any issues, I get the following error:

_Activating extensions
Preparing
LLVM ERROR: Symbol not found: __svml_cosf8_ha_

And no other option but to close the CMD window.
Running it once more does indeed skip the installation process but results in the same error.

**Expected behavior**
The UI just starts without any issues

I'm running Python 3.10.6 and never experienced this although running a plethora of AI applications which I usually just installed from Github without the help of any dedicated installer.

**Comment by gitmylo** [comment]
This comment: https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093 might be of interest.
This bug is not related to audio-webui itsself, so I will be closing the issue, if you still need help, you can ask it in this issue.

**Comment by Sunflex616** [comment]
In fact, following the instructions from your posted comment helped.
Now, unfortunately, I run into the next problem:

```
Downloading (…)_schema%400.0.3.json: 100%|████████████████████████████████████████████████| 13.1k/13.1k [00:00<?, ?B/s]
Traceback (most recent call last):
  File "L:\audio-webui\main.py", line 38, in <module>
    autodebug.catcher(e)
  File "L:\audio-webui\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "L:\audio-webui\main.py", line 35, in <module>
    launch_webui()
  File "L:\audio-webui\webui\webui.py", line 27, in launch_webui
    create_ui(args.theme).queue().launch(share=args.share,
  File "L:\audio-webui\webui\ui\ui.py", line 104, in create_ui
    content()
  File "L:\audio-webui\webui\ui\tabs\text_to_speech.py", line 29, in text_to_speech
    all_components_dict = tts_models.all_elements_dict()
  File "L:\audio-webui\webui\modules\implementations\ttsmodels.py", line 370, in all_elements_dict
    d[tts.model] = tts.gradio_components()
  File "L:\audio-webui\webui\modules\models.py", line 95, in gradio_components
    components = self._components(interactive=True, visible=False)
  File "L:\audio-webui\webui\modules\implementations\ttsmodels.py", line 280, in _components
    selected_tts = gradio.Dropdown(TTS.list_models(), label='TTS model', info='The TTS model to use for text-to-speech',
TypeError: TTS.list_models() missing 1 required positional argument: 'self'
```
Which forces me to close the programme again.

**Comment by gitmylo** [comment]
It looks like coqui updated 3 hours ago and completely changed the list_models function in this commit https://github.com/coqui-ai/TTS/commit/3a104d5c49e6f9063e32ba5fed8e34f1dce25887. It now requires TTS to be instantiated before using list_models(), i'll see if that fixes it

**Comment by Sunflex616** [comment]
What a fortunate timing for me to try to get it running, haha.
I'm excited to see if that fixes it :)

**Comment by gitmylo** [comment]
Fixed in https://github.com/gitmylo/audio-webui/commit/13f2ec556b5a08889864f8ae7a894721e8d1319d

**Comment by Sunflex616** [comment]
Seems to work (at least it does start now). 
Thanks for your help! :)

**Comment by vindhyasreegangasani** [comment]
I am facing the same error when i am trying to create a web page for my Audio classification. Can someone please help

LLVM ERROR: Symbol not found: __svml_cosf8_ha

**Comment by gitmylo** [comment]
> I am facing the same error when i am trying to create a web page for my Audio classification. Can someone please help
> 
> LLVM ERROR: Symbol not found: __svml_cosf8_ha

Have you tried the solution listed above? (https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093)

**Comment by vindhyasreegangasani** [comment]
> > I am facing the same error when i am trying to create a web page for my Audio classification. Can someone please help
> > LLVM ERROR: Symbol not found: __svml_cosf8_ha
> 
> Have you tried the solution listed above? ([lmcinnes/umap#702 (comment)](https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093))

Yes, yes..I did!!!
