### ISSUE TITLE
build wheels for tts [BUG REPORT] 

### ISSUE THREAD

**Issue by nookie-dotcom** [gitmylo/audio-webui#108]
I got this working like a charm before. So thanks! for this amazing script. 
Anyway i'm on a fresh win10 installed today, got python, anaconda, git, VS and when it start the run.bat it comes to installing tts i get the following error. Could you please help me once again? Do you need more debug-output?

error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for tts
ERROR: Could not build wheels for tts which use PEP 517 and cannot be installed directly

**Comment by gitmylo** [comment]
exit code 2 means a file was not found according to winerror.h https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499- can you check if you have the build tools correctly installed?

**Comment by nookie-dotcom** [comment]
there's a vs_BuildTools.exe and a VisualStudioSetup.exe...
that's my screenshot of VS install, still exit code 2 -> 
![Capture](https://github.com/gitmylo/audio-webui/assets/61462021/66d63e0b-c467-4401-bebc-ee07b55c7477)

**Comment by gitmylo** [comment]
I'm not sure, the error is related to either the build tools not being found, or the build tools not being able to find some file that is required for install.

Also, you mentioned you used anaconda, maybe you can try it using venv (just don't supply --skip-venv in the run script, and it will create and activate and manage the venv for you)

**Comment by nookie-dotcom** [comment]
Solution: purge VisualStudioSetup, Anaconda and go with the vs_BuildTools.exe and the official Python 3.10 **only**.

**Comment by gitmylo** [comment]
Great that you found a solution!

**Comment by nookie-dotcom** [comment]
can i contact you on mastodon or lemmy or do you have an ethereum address? I really would like to spend you some crypto... my mail is la_pythia@proton.me

**Comment by gitmylo** [comment]
My ethereum address is 0x377FdE378b9dEB0A5a0f5cCb09DEF6A53736b817, if you want to donate, I don't have a mastodon or lemmy account.
