### ISSUE TITLE
Where are the outputs ?

### ISSUE THREAD

**Issue by BMontens** [gitmylo/audio-webui#109]
There's no "outputs" folder, so where does the generated audio go ?

**Comment by gitmylo** [comment]
Generated audios + waveform videos are stored in your system's cache folder currently. It might be a good idea for me to change that to a new folder.

For now, you can download audio with right click on the audio, and you can download videos by pressing the download button in the top left.

**Comment by gitmylo** [comment]
The new default temp dir is now `data/temp`, you can change it to something else by setting the `GRADIO_TEMP_DIR` env variable
