### ISSUE TITLE
[BUG REPORT] Saves every n epoch even when its been disabled

### ISSUE THREAD

**Issue by G-force78** [gitmylo/audio-webui#111]
**Describe the bug**

**To Reproduce**

Start training, either put in 0 or leave blank in `Save every n epoch`s

**Expected behavior**

Ignores any saving until the model has finished training

**Screenshots**

**Additional context**

**Comment by gitmylo** [comment]
That's weird, what does it say in the `workspace.json` from the `data/training/rvc/name/workspace.json`? It works normally for me.

**Comment by G-force78** [comment]
Seems to be ok for that today, although for some reason it changed my batch from 2 to 3 lol 
Is there a way to see the progress in real time? I'm not sure if its failed it seems to be hung. I assume pitch extraction is optional?
**UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
v2 40k
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
<All keys matched successfully>**

![saveepochs](https://github.com/gitmylo/audio-webui/assets/114336644/f5705c1d-e772-45f3-b1ed-ab56c9456690)

**Comment by gitmylo** [comment]
Pitch extraction is optional, but highly recommended.

Good to see you got it working, the config might not have saved yet, maybe due to a browser difference with the onChange event triggering at a different time.

**Comment by gitmylo** [comment]
Also, it's not stuck, it's done training, as indicated by the lack of an outline around the info, and the info message which says "Finished training. Saving..."
