### ISSUE TITLE
this massage came up to me when installing audio webui , how do i fix it ?

### ISSUE THREAD

**Issue by Subzero22999** [gitmylo/audio-webui#113]
![Untitled](https://github.com/gitmylo/audio-webui/assets/137317361/29ce7263-49d5-4bfe-9882-c2eca36a86a9)
Install failed!
STDOUT:
Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting future
  Using cached future-0.18.3-py3-none-any.whl

STDERR:
ERROR: Wheel 'future' located at C:\users\subze\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\5e\a9\47\f118e66afd12240e4662752cc22cefae5d97275623aa8ef57d\future-0.18.3-py3-none-any.whl is invalid.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by gitmylo** [comment]
delete the cached wheel at `C:\users\subze\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\5e\a9\47\f118e66afd12240e4662752cc22cefae5d97275623aa8ef57d\future-0.18.3-py3-none-any.whl`

**Comment by Subzero22999** [comment]
Thank u so much , it worked
