### ISSUE TITLE
[BUG REPORT] RuntimeError: The size of tensor a (28) must match the size of tensor b (33) at non-singleton dimension 2

### ISSUE THREAD

**Issue by mikeymcfish** [gitmylo/audio-webui#129]
I get this error when I try to train an RVC model. I've tried various settings, different audio files, re-installing, and running on runpod.

RuntimeError: The size of tensor a (28) must match the size of tensor b (33) at non-singleton dimension 2

**Comment by gitmylo** [comment]
Use RVC v1 40k or v2 40k, 48k is not currently supported.
