### ISSUE TITLE
[FEATURE REQUEST] Conda

### ISSUE THREAD

**Issue by Blazzycrafter** [gitmylo/audio-webui#140]
**Is your feature request related to a problem? Please describe.**
> i have py 3.11
> i have py 3.7
> ... these problems

**Describe the solution you'd like**
> check if conda is installed
> if conda is installed use `conda create --name audio-webui python=3.10` to create an conda env
> if conda is installed use conda `activate audio-webui` to activate the conda env.... then all "i have py x.xx" broblems should been solved

**Comment by gitmylo** [comment]
Conda is not officially supported, but works fine when using the `--skip-venv` flag, there are also no plans to add conda.

If you're on windows, and have the python.org version of python installed, with py launcher, it will use 3.10 automatically, no issues if you also have other versions installed.

On linux, it will use the python3.10 command, also ensuring it uses the right version.
