### ISSUE TITLE
Installing TTS Step in the installer bat file

### ISSUE THREAD

**Issue by benc1221** [gitmylo/audio-webui#147]
there seems to be an issue with this step because it just hang there and i can never get passed this part, is this a bug or is it me installing it wrongly?

**Comment by gitmylo** [comment]
What do you mean by hanging? Does it keep loading?

TTS is a large package, so on computers with slower internet, or other limitations, it might take a bit to install.

**Comment by benc1221** [comment]
yes it just stays in that phase i had been waiting for 2 hours and last 2 weeks ago it was instant install but now i have no idea why is this happening.

**Comment by gitmylo** [comment]
That's odd, can you try manually installing?

1. run `activate_only.bat`/`activate_only.sh` to activate the virtual environment
2. type `pip install --upgrade TTS` and press enter

**Comment by benc1221** [comment]
is this normal for pip to be struggling like this? INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
Collecting idna<4,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
  Using cached idna-2.7-py2.py3-none-any.whl (58 kB)
  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
  Using cached idna-2.5-py2.py3-none-any.whl (55 kB)
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
Collecting chardet<5,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
  Using cached chardet-3.0.3-py2.py3-none-any.whl (133 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached chardet-3.0.2-py2.py3-none-any.whl (133 kB)
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
Collecting clean-fid
  Using cached clean_fid-0.1.33-py3-none-any.whl (25 kB)
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
  Using cached clean_fid-0.1.32-py3-none-any.whl (26 kB)

**Comment by benc1221** [comment]
it just stops at clean_fid dependency and it wont progress

**Comment by benc1221** [comment]
ok so upgrading pip seems to fix the issue

**Comment by gitmylo** [comment]
Okay, great!
