### ISSUE TITLE
[BUG REPORT] Bark's `speaker.npz` download link is invisible

### ISSUE THREAD

**Issue by SuperUserNameMan** [gitmylo/audio-webui#153]
Hello there,

I was wondering why it was not possible to download the `speaker.npz` file generated by Bark.

In fact it was jsut invisible because of this `white !important` CSS rule :

https://github.com/gitmylo/audio-webui/blob/0ad6bddb58d731eb0058572e1387911689fb485b/webui/ui/ui.py#L48C1-L49C52

**Comment by gitmylo** [comment]
What do you mean? The download button is white instead of blue, but it still says "download"

**Comment by SuperUserNameMan** [comment]
Sorry, I should have put this screenshot sooner.

Model : `suno/bark`
Speaker from : `File/None`

![Screenshot 2023-10-05 at 10-32-42 Audio WebUI](https://github.com/gitmylo/audio-webui/assets/9801802/2357ff5c-0e65-47c0-86d5-966e8d9e45a3)

**Comment by gitmylo** [comment]
Oh, yeah, I understand now. I've only been using the dark theme since my system has a dark theme. I didn't think about that, I can probably just invert based on the theme colors.
