### ISSUE TITLE
[BUG REPORT] Audiocraft install fails

### ISSUE THREAD

**Issue by Tampa** [gitmylo/audio-webui#154]
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 0ad6bddb58d731eb0058572e1387911689fb485b - Mon Oct 2 18:14:57 2023 +0200
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 0ad6bddb58d731eb0058572e1387911689fb485b - Mon Oct 2 18:14:57 2023 +0200
Found extensions:
Installed PyTorch!
Failed to install audiocraft. Check AutoDebug output.

Install failed!
STDOUT:
Collecting git+https://github.com/facebookresearch/audiocraft.git
  Cloning https://github.com/facebookresearch/audiocraft.git to c:\users\admin\appdata\local\temp\pip-req-build-u2qyyf1p
  Resolved https://github.com/facebookresearch/audiocraft.git to commit a2b96756956846e194c9255d0cdadc2b47c93f1b
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting av
  Using cached av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
Requirement already satisfied: einops in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.6.1)
Collecting flashy>=0.0.1
  Using cached flashy-0.0.2.tar.gz (72 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting hydra-core>=1.1
  Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Collecting hydra_colorlog
  Using cached hydra_colorlog-1.2.0-py3-none-any.whl (3.6 kB)
Requirement already satisfied: julius in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.2.7)
Requirement already satisfied: num2words in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.5.12)
Requirement already satisfied: numpy in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (1.23.5)
Requirement already satisfied: sentencepiece in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.1.99)
Collecting spacy==3.5.2
  Using cached spacy-3.5.2-cp310-cp310-win_amd64.whl (12.2 MB)
Requirement already satisfied: torch>=2.0.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (2.1.0)
Requirement already satisfied: torchaudio>=2.0.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (2.1.0)
Requirement already satisfied: huggingface_hub in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.17.1)
Requirement already satisfied: tqdm in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (4.64.1)
Requirement already satisfied: transformers>=4.31.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (4.33.3)
Collecting xformers
  Using cached xformers-0.0.22-cp310-cp310-win_amd64.whl (97.6 MB)
Requirement already satisfied: demucs in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (4.1.0a1)
Requirement already satisfied: librosa in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.9.1)
Requirement already satisfied: gradio in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (3.35.2)
Collecting torchmetrics
  Using cached torchmetrics-1.2.0-py3-none-any.whl (805 kB)
Requirement already satisfied: encodec in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (0.1.1)
Requirement already satisfied: protobuf in g:\audio-webui\audio-webui\venv\lib\site-packages (from audiocraft==1.0.0) (4.24.4)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.8-cp310-cp310-win_amd64.whl (39 kB)
Collecting thinc<8.2.0,>=8.1.8
  Using cached thinc-8.1.12-cp310-cp310-win_amd64.whl (1.5 MB)
Collecting catalogue<2.1.0,>=2.0.6
  Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting typer<0.8.0,>=0.3.0
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
Collecting wasabi<1.2.0,>=0.9.1
  Using cached wasabi-1.1.2-py3-none-any.whl (27 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.9-cp310-cp310-win_amd64.whl (122 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.10-cp310-cp310-win_amd64.whl (25 kB)
Collecting langcodes<4.0.0,>=3.2.0
  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0
  Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting smart-open<7.0.0,>=5.2.1
  Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Collecting pathy>=0.10.0
  Using cached pathy-0.10.2-py3-none-any.whl (48 kB)
Requirement already satisfied: setuptools in g:\audio-webui\audio-webui\venv\lib\site-packages (from spacy==3.5.2->audiocraft==1.0.0) (63.2.0)
Collecting srsly<3.0.0,>=2.4.3
  Using cached srsly-2.4.8-cp310-cp310-win_amd64.whl (481 kB)
Requirement already satisfied: jinja2 in g:\audio-webui\audio-webui\venv\lib\site-packages (from spacy==3.5.2->audiocraft==1.0.0) (3.1.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from spacy==3.5.2->audiocraft==1.0.0) (2.31.0)
Requirement already satisfied: packaging>=20.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from spacy==3.5.2->audiocraft==1.0.0) (23.1)
Collecting pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4
  Using cached pydantic-1.10.13-cp310-cp310-win_amd64.whl (2.1 MB)
Requirement already satisfied: dora-search in g:\audio-webui\audio-webui\venv\lib\site-packages (from flashy>=0.0.1->audiocraft==1.0.0) (0.1.12)
Collecting colorlog
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting omegaconf<2.4,>=2.2
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Requirement already satisfied: networkx in g:\audio-webui\audio-webui\venv\lib\site-packages (from torch>=2.0.0->audiocraft==1.0.0) (2.8.8)
Requirement already satisfied: typing-extensions in g:\audio-webui\audio-webui\venv\lib\site-packages (from torch>=2.0.0->audiocraft==1.0.0) (4.8.0)
Requirement already satisfied: fsspec in g:\audio-webui\audio-webui\venv\lib\site-packages (from torch>=2.0.0->audiocraft==1.0.0) (2023.6.0)
Requirement already satisfied: filelock in g:\audio-webui\audio-webui\venv\lib\site-packages (from torch>=2.0.0->audiocraft==1.0.0) (3.12.4)
Requirement already satisfied: sympy in g:\audio-webui\audio-webui\venv\lib\site-packages (from torch>=2.0.0->audiocraft==1.0.0) (1.12)
Requirement already satisfied: colorama in g:\audio-webui\audio-webui\venv\lib\site-packages (from tqdm->audiocraft==1.0.0) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in g:\audio-webui\audio-webui\venv\lib\site-packages (from transformers>=4.31.0->audiocraft==1.0.0) (0.13.3)
Requirement already satisfied: regex!=2019.12.17 in g:\audio-webui\audio-webui\venv\lib\site-packages (from transformers>=4.31.0->audiocraft==1.0.0) (2023.10.3)
Requirement already satisfied: safetensors>=0.3.1 in g:\audio-webui\audio-webui\venv\lib\site-packages (from transformers>=4.31.0->audiocraft==1.0.0) (0.3.3)
Requirement already satisfied: pyyaml>=5.1 in g:\audio-webui\audio-webui\venv\lib\site-packages (from transformers>=4.31.0->audiocraft==1.0.0) (6.0.1)
Requirement already satisfied: lameenc>=1.2 in g:\audio-webui\audio-webui\venv\lib\site-packages (from demucs->audiocraft==1.0.0) (1.6.1)
Requirement already satisfied: openunmix in g:\audio-webui\audio-webui\venv\lib\site-packages (from demucs->audiocraft==1.0.0) (1.2.1)
Requirement already satisfied: gradio-client>=0.2.7 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.5.3)
Requirement already satisfied: pygments>=2.12.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (2.16.1)
Requirement already satisfied: python-multipart in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.0.6)
Requirement already satisfied: ffmpy in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.3.1)
Requirement already satisfied: pandas in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (1.5.3)
Requirement already satisfied: websockets>=10.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (11.0.3)
Requirement already satisfied: pillow in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (10.0.1)
Requirement already satisfied: mdit-py-plugins<=0.3.3 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.3.3)
Requirement already satisfied: altair>=4.2.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (5.1.2)
Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (2.2.0)
Requirement already satisfied: uvicorn>=0.14.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.23.2)
Requirement already satisfied: aiofiles in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (23.2.1)
Requirement already satisfied: pydub in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.25.1)
Requirement already satisfied: markupsafe in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (2.1.3)
Requirement already satisfied: fastapi in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.103.2)
Requirement already satisfied: aiohttp in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (3.8.5)
Requirement already satisfied: semantic-version in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (2.10.0)
Requirement already satisfied: httpx in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (0.25.0)
Requirement already satisfied: orjson in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (3.9.7)
Requirement already satisfied: matplotlib in g:\audio-webui\audio-webui\venv\lib\site-packages (from gradio->audiocraft==1.0.0) (3.7.3)
Requirement already satisfied: numba>=0.45.1 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (0.57.0)
Requirement already satisfied: joblib>=0.14 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (1.3.2)
Requirement already satisfied: audioread>=2.1.5 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (3.0.1)
Requirement already satisfied: pooch>=1.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (1.7.0)
Requirement already satisfied: soundfile>=0.10.2 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (0.12.1)
Requirement already satisfied: scikit-learn>=0.19.1 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (1.3.0)
Requirement already satisfied: scipy>=1.2.0 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (1.11.3)
Requirement already satisfied: resampy>=0.2.2 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (0.4.2)
Requirement already satisfied: decorator>=4.0.10 in g:\audio-webui\audio-webui\venv\lib\site-packages (from librosa->audiocraft==1.0.0) (5.1.1)
Requirement already satisfied: docopt>=0.6.2 in g:\audio-webui\audio-webui\venv\lib\site-packages (from num2words->audiocraft==1.0.0) (0.6.2)
Collecting lightning-utilities>=0.8.0
  Using cached lightning_utilities-0.9.0-py3-none-any.whl (23 kB)
Collecting xformers
  Using cached xformers-0.0.21-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached xformers-0.0.20-cp310-cp310-win_amd64.whl (97.6 MB)
Collecting pyre-extensions==0.0.29
  Using cached pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Collecting xformers
  Using cached xformers-0.0.19-cp310-cp310-win_amd64.whl (96.7 MB)
  Using cached xformers-0.0.18-cp310-cp310-win_amd64.whl (112.3 MB)
Collecting pyre-extensions==0.0.23
  Using cached pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting xformers
  Using cached xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
  Using cached xformers-0.0.16-cp310-cp310-win_amd64.whl (40.0 MB)
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

STDERR:
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/audiocraft.git 'C:\Users\Admin\AppData\Local\Temp\pip-req-build-u2qyyf1p'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Admin\AppData\Local\Temp\pip-install-sy4q2p7i\xformers_f25109dd6fc14bd8beebf21bee6b345c\setup.py", line 239, in <module>
      ext_modules=get_extensions(),
    File "C:\Users\Admin\AppData\Local\Temp\pip-install-sy4q2p7i\xformers_f25109dd6fc14bd8beebf21bee6b345c\setup.py", line 157, in get_extensions
      raise RuntimeError(
  RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by gitmylo** [comment]
The issue should be resolved now, pulling the new changes should fix it.

**Comment by gitmylo** [comment]
Try manually activating the venv and running "pip uninstall audiocraft"

**Comment by Tampa** [comment]
It's not installed so it just skips
(venv) pip uninstall audiocraft
WARNING: Skipping audiocraft as it is not installed.

**Comment by Tampa** [comment]
Went into venv, upgraded pip to latest version. Installed xformers manually. run.bat now completes.

**Comment by gitmylo** [comment]
Alright, great

**Comment by JohnnyStreet** [comment]
This did not fix the issue for me.
