### ISSUE TITLE
Suggestion - upgrade pip at start of install

### ISSUE THREAD

**Issue by SoftologyPro** [gitmylo/audio-webui#16]
Saves all these warnings as install happens.

```
[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement pyworld>=0.3.2...

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement faiss-cpu==1.7.3...

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement torchcrepe==0.0.18...
```

Also, maybe show all stats as each package installs.  Helps those with slow connections see the install is still running and assume it has hung.

**Comment by gitmylo** [comment]
i'll change the disabling of outputs to be a flag instead of always on then

**Comment by SoftologyPro** [comment]
> `--upgrade pip` isn't possible due to the python environment calling the commands being the same as the one pip is installed with, this would lead to an error during the install and pip not working anymore, requiring a reinstall.

I do it all the time.  After you activate your venv, run this as the first command.
`python.exe -m pip install --upgrade pip`
Then pip is upgraded within the venv.

**Comment by genevera** [comment]
> `--upgrade pip` isn't possible due to the python environment calling the commands being the same as the one pip is installed with, this would lead to an error during the install and pip not working anymore, requiring a reinstall.

It's definitely doable...

```bash
⌁ [genevera:~/.local/src/audio-webui ⚞3] [2.7.4] master(+0/-0)* ± source venv/bin/activate
⌁ [genevera:~/.local/src/audio-webui ⚞3] [venv] [2.7.4] master(+0/-0)* ± which python3
/Users/genevera/.local/src/audio-webui/venv/bin/python3
⌁ [genevera:~/.local/src/audio-webui ⚞3] [venv] [2.7.4] master(+0/-0)* ± python3 -m pip install -U pip
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (23.0.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.1.2
⌁ [genevera:~/.local/src/audio-webui ⚞3] [venv] [2.7.4] master(+0/-0)* 16s 130 ± ./run.sh --skip-install
Checking installs and venv
Monkeypatching bark
Launching, cuda available: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by gitmylo** [comment]
I'm on windows, when I tried it, pip uninstalled and then failed to reinstall, and I had to recreate my venv.
I don't feel safe pushing something like this for just linux, because I don't know which distros will work and which ones won't. If windows doesn't work, I can't be sure about linux always working either.
