### ISSUE TITLE
Multi Voice Models and tortoise.

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#18]
I had to edit the TTS python module to set strict=False in order to load tortoise and it does some slow but great inputs. However the voice is still locked to only male and cannot be changed. Quite a few models have this problem where the "good" tts only has one voice or it won't run at all due to no speaker being selected.

We can choose the speaker for RVC models, how about for other TTS.

**Comment by gitmylo** [comment]
I could add that, yes
