### ISSUE TITLE
[FEATURE REQUEST] Cloned bark voices .npz aren't saved with the same filename as audio file anymore

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#19]
They're now saved as "tmp[randomlettersandnumbers].npz" Old way of auto-naming cloned voices was more convenient.

**Comment by gitmylo** [comment]
correct, i would need a workaround though, since using an audio element is way nicer than using a file element. as it lets you preview and cut the audio. files don't let you do that.

i could add a textbox where you type the name for your clone

**Comment by gitmylo** [comment]
Added a textbox to specify a custom filename to save your custom speaker as
