### ISSUE TITLE
[BUG REPORT] Exception: "reflection_pad1d" not implemented for 'Short'

### ISSUE THREAD

**Issue by robonxt** [gitmylo/audio-webui#196]
**Describe the bug**
Been getting errors when I try to use whisper on a audio file converted with Audacity to 16000hz, signed 16 PCM, WAV format:
`Exception: "reflection_pad1d" not implemented for 'Short'`

**To Reproduce**
1. Use Audacity to convert a english memo mp3 file into wav with 16000hz, signed 16 PCM, WAV format
2. Upload to Audio WebUI
3. Load any whisper model (I used base) 
4. Click `Transcribe` button
5. See error

**Expected behavior**
whisper should be transcribing my audio.

**Additional context**
I tried it on the OG whisper.cpp and it works normally.

**Comment by gitmylo** [comment]
Try uploading the file into the batch section, gradio does some conversions before I get access to the audio, which are kind of unpredictable.

**Comment by robonxt** [comment]
Hmm, I've found that by accident. Guess it's gradio issue. Will close this.
