### ISSUE TITLE
[Solved] In Queue Forever... Pinokio

### ISSUE THREAD

**Issue by SmoothPlay** [gitmylo/audio-webui#199]
**Describe the bug**
App is working, no errors. Just stays on queue forever whichever tool I try to use.

**To Reproduce**
1. Go to any of the tools
2. Click or Interact with any of tools
3. Wait forever in a queue

**Expected behavior**
Either show any error or succeed in processing the queue and being able to use the tools.

**Additional context**
Ubuntu 23.10
RTX 3060 12gb vRam (using Cuda) 
Installed via Pinokio (  but also previously tried installing it normally but with no success )

This seems to be a very promising tool, with a compilation of very useful audio tools, but unfortunately I never succeeded to make it work.

**Comment by gitmylo** [comment]
Did you fail to install normally or did it have the same issue?

**Comment by SmoothPlay** [comment]
> Did you fail to install normally or did it have the same issue?

Same issue. I did manage to install manually but also couldn't do anything with the tools.

Can you please clarify me on some things, for example, are we supposed to install every model manually? 

I did try to install tts via tts.json, but the both tts still keep loading forever.

I did manually pasted some rvc models to RVC but the tool has the same loading forever behavior.

When I say loading, I mean Queue. 

Same with all of the other tools.

**Comment by gitmylo** [comment]
Only RVC models need to be installed manually, the other models download automatically.

**Comment by SmoothPlay** [comment]
> Only RVC models need to be installed manually, the other models download automatically.

Thank you, then I suppose something is really wrong.

It detects the GPU, runs without any errors, just gets stuck on queue. 

Model folders are empty, perhaps the problem has to do with Downloading the models?

**Comment by gitmylo** [comment]
It downloads the models as soon as they're needed. People had issues downloading bark models in the past, but it would not show it as being queued, it was already downloading.

**Comment by SmoothPlay** [comment]
I see, does this App save a log somewhere? Even though no warning or error is printed, maybe it would be a good idea to check it out.

**Comment by SmoothPlay** [comment]
Here goes, got an error. 

2024-01-04 17:37:41 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='shsc3aa0119_10' coro=<Queue.process_events() done, defined at /media/studios/TOSHIBA4TB/AI/AI/api/audio-webui/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['suno/bark'], '...on_hash': 'shsc3aa0119'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "/media/studios/TOSHIBA4TB/AI/AI/api/audio-webui/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/media/studios/TOSHIBA4TB/AI/AI/api/audio-webui/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/media/studios/TOSHIBA4TB/AI/AI/api/audio-webui/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/media/studios/TOSHIBA4TB/AI/AI/api/audio-webui/audio-webui/venv/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['suno/bark'], '...on_hash': 'shsc3aa0119'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by SmoothPlay** [comment]
One small detail, RVC models are not even seen by the app... 

This seems like a permission issue... The folders permission are chown to the normal user.  This this app require some special user permission for the folders?

**Comment by gitmylo** [comment]
Audio-webui should not need any special permissions, unless the folder it's in needs them of course

**Comment by SmoothPlay** [comment]
Amazing, got this finally working.

For anyone installing this via Pinokio, here is the thing:

On the file install.json, strangely the app was git cloning from another unofficial repository.

So just change the 
"message": "git clone https://github.com/cocktailpeanut/audio-webui.git" 

to the official repository: 
"message": "git clone https://github.com/gitmylo/audio-webui.git"

It works :) I'll test further to see if there is anything broken.

And if you had install errors before it is most likely because of some needed dependencies, so just pip install those.

Thank you gitmylo for the help and I'm sorry that this isn't actually related to your repo, it was just a coincidence that for some reason it didn't work when I manually installed it before.

**Comment by SmoothPlay** [comment]
I can confirmed it is now fully working, nothing broken. Cool.

Just as a curiosity, XTTS (coqui) was removed?  Only bark visible now.
And are there any valuable extensions list? 
I would love to install as much tools and models as possible.

**Comment by gitmylo** [comment]
Coqui is available through the [TTS extension](https://github.com/gitmylo/audio-webui-TTS-extension) since it was causing too many issues throughout updates, I decided to just move it to an external extension.

**Comment by SmoothPlay** [comment]
> Coqui is available through the [TTS extension](https://github.com/gitmylo/audio-webui-TTS-extension) since it was causing too many issues throughout updates, I decided to just move it to an external extension.

Thank you, I'm closing this issue as it is solved.
