### ISSUE TITLE
Install/Setup for Mac

### ISSUE THREAD

**Issue by imomin** [gitmylo/audio-webui#2]
Do you have instruction for running this project on Mac? I get following error when I execute run.sh.
```

Checking installs and venv
activating venv
sh: bin/activate: No such file or directory
Press any key to exit...


```

**Comment by imomin** [comment]
I added following f'{venv_name} after else.

venv_activate_path = f'{venv_name}/' + 'Scripts/activate.bat' if is_windows() else f'{venv_name}/bin/activate'

**Comment by gitmylo** [comment]
This was added (slightly differently) in commit bb8ace31447392efb5877059893fda732a5adcb4
