### ISSUE TITLE
[FEATURE REQUEST]  MusicGen addition

### ISSUE THREAD

**Issue by frandmb** [gitmylo/audio-webui#20]
Facebook released MusicGen (https://github.com/facebookresearch/audiocraft). Is this something that this client should support?

**Comment by gitmylo** [comment]
Yes, audiocraft does fit the project scope.

**Comment by gitmylo** [comment]
Audiocraft has been implemented (Tested: Medium model, Melody model, conditional, unconditional, with melody)

have fun!
