### ISSUE TITLE
[BUG REPORT] Pitch extraction silently fails.

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#22]
I have 4gb of data that I am processing into RVC numpy's. The audio is cut fine but the pitch extraction is failing silently. There are about 8000 files it makes per folder and keeps failing on the last or second to last, regardless of whether I use chrome or firefox.

Since it can't pick up where it left off, I always have to start again and it's not failing on the same file.

**Comment by gitmylo** [comment]
4 gigabytes overkill, that would probably overtrain the model before even one epoch, unless your audio data is somehow extremely large file-size,

for the pitch extraction, I'll make it continue then, but you'll have to delete the folders if you want to switch pitch extraction method

**Comment by Ph0rk0z** [comment]
I found what it was. The logs in the status box were crashing the browser. I stopped outputting "processing" and "extracting pitch" then it successfully completed.

As for over training, I think it came out that way. This audio is only 3 videos of someone streaming. Previous model was one and I think that came out better. Seems 1000 steps is sort of a sweet spot. The previous estimator used too few, about 10 epochs was good. Current one I need to re-run at about 4-5 vs the 1 it recommends. 

Ironically, sometimes the over trained models do better on certain samples. This is just talking so singing might be a different story.

2.0 is a good loss here? I'm used to LLMs where 1.5-1.0 was the zone before it got too much of the material. I never found any best practices so I'm winging it and trying things.

**Comment by gitmylo** [comment]
yeah, i'm still trying to find the sweet spot for the amount of training, it can still depend a lot on the audio.

the exact number in the loss is not important, just the loss relative to the previous losses is important, if it becomes unstable, you're overtraining, and need to take a previous checkpoint
