### ISSUE TITLE
[BUG REPORT] Pinokio unable to install

### ISSUE THREAD

**Issue by SkelegonDK** [gitmylo/audio-webui#227]
**Describe the bug**
Pinokio Is unable to install Audio WebUI on Mac

**To Reproduce**
Install Pinokio
Download Audio Webui
Press install

**Expected behavior**
Install successfull

**Screenshots**
`
STDERR:
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running dist_info
      creating /Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info
      writing /Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/PKG-INFO
      writing dependency_links to /Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/dependency_links.txt
      writing requirements to /Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/requires.txt
      writing top-level names to /Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/top_level.txt
      writing manifest file '/Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/SOURCES.txt'
      reading manifest file '/Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pxd' under directory 'pyworld'
      adding license file 'LICENSE'
      writing manifest file '/Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld.egg-info/SOURCES.txt'
      creating '/Users/manuelthomsen/pinokio/cache/TMPDIR/pip-modern-metadata-s75gcvm6/pyworld-0.3.4.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]
`

**Additional context**

**Comment by gitmylo** [comment]
I am not affiliated with pinokio, but the error implies the venv is missing wheel. Which can be installed with `pip install wheel`.
