### ISSUE TITLE
 Failed building wheel for fairseq

### ISSUE THREAD

**Issue by tabulak0** [gitmylo/audio-webui#233]
**Describe the bug**
Always when I start installation I see this problem. I have python 3.10.11. I instal Microsoft C++ Build Tools and Windows SDK. I don't know what to do 

**To Reproduce**
1. Go to audio-webui
2. Click on run.bat
3. installing procces

 running build_ext
  building 'fairseq.libbleu' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip

You need to have visual studio C++ build tools installed. https://visualstudio.microsoft.com/visual-cpp-build-tools/.
Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 1

**Comment by gitmylo** [comment]
Error seems self explanatory

**Comment by gitmylo** [comment]
[This might help](https://github.com/gitmylo/audio-webui/issues/98#issuecomment-1664202737)

**Comment by tabulak0** [comment]
ehhh i give up. I dont know what im doing wrong
