### ISSUE TITLE
[QUESTION] How to resolve "Prompt is longer than audio to generate"?

### ISSUE THREAD

**Issue by Stonley890** [gitmylo/audio-webui#244]
# How do I resolve the error "AssertionError: Prompt is longer than audio to generate" using AudioCraft?
If the audio clip prompt for AudioCraft is too long, it will throw this error, no matter how long the duration is set to. What am I missing here?

**Comment by gitmylo** [comment]
I believe the duration needs to be greater than the input audio, but if that doesn't work, it might be something else related to the audio.
