### ISSUE TITLE
[FEATURE REQUEST] Crepe hop length option for RVC training workspaces

### ISSUE THREAD

**Issue by gitmylo** [gitmylo/audio-webui#27]
As the title suggests, implement crepe hop length for RVC training workspaces. As lower hop length can improve training even more. Although the dataset preparation will take a bit longer.

**Comment by nekogecko2** [comment]
It's disabled. When I hover over the slider or number editor, my mouse turns into the  🚫 icon

**Comment by gitmylo** [comment]
> It's disabled. When I hover over the slider or number editor, my mouse turns into the 🚫 icon

Probably because it's only used as an output code wise, i'll make sure gradio makes it interactive
