### ISSUE TITLE
[BUG REPORT] Tortoise-v2 TTS model doesn't load

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#28]
I get this error

```
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".
```

Additionally is there a config file available to change the generation settings in tortoise?

**Comment by gitmylo** [comment]
the coqui TTS is just for general generations, so no, it does not have configs.

I am also unable to reproduce that error. I did see someone say they wanted to use tortoise v2 and had the same issue. not sure where the flag was that they were talking about

**Comment by Ph0rk0z** [comment]
It's right where that error is. The strict=False has to be passed when loading the model. It maybe a problem with the coqui repo. I manually edited the file for myself. Does TTS python expose that so it can be set as a parameter?

In any case, tortoise here only uses one male voice. I even swapped my trained model for it and then it would do 1/2 in the trained voice and 1/2 in the voice of the dude. Tortoise would have to be done on it's own for max effect so I usually use mr_q ai voice cloning for that unless the TTS voice doesn't matter.

**Comment by gitmylo** [comment]
i don't know, as i have no issues loading tortoise v2 in coqui. i'm on windows 10, what OS are you on?

**Comment by Ph0rk0z** [comment]
Linux Mint based on ubuntu 22.04

**Comment by nekogecko2** [comment]
I'm using windows 11. But the same error happens when I run it with "linux" through WSL.

**Comment by gitmylo** [comment]
whoops, i misclicked

**Comment by Ph0rk0z** [comment]
Probably windows doesn't enforce strict dictionary loading.

**Comment by gitmylo** [comment]
but nekogecko2 is on windows, so that isn't it

**Comment by Ph0rk0z** [comment]
Different versions of TTS? Would have to go through coqui github and see what happened with that. It's a problem for LLMs too. Dict slightly doesn't match and then it doesn't load at all.

**Comment by gitmylo** [comment]
I'm on version 0.14.3, which is currently the latest version on pypi

**Comment by Ph0rk0z** [comment]
I think me too since I d/l it fairly recently. Back to square one.

**Comment by nekogecko2** [comment]
Could this be the fix for it?

https://github.com/coqui-ai/TTS/pull/2697

**Comment by gitmylo** [comment]
> Could this be the fix for it?
> 
> [coqui-ai/TTS#2697](https://github.com/coqui-ai/TTS/pull/2697)

it might be, try activating your virtual environment and running
`pip install git+https://github.com/coqui-ai/TTS@dev`

**Comment by Ph0rk0z** [comment]
Makes too much sense. New transformers enforced more strictness. Instead of setting strict false they.. removed the extra keys.

**Comment by gitmylo** [comment]
¯\_(ツ)_/¯

**Comment by Ph0rk0z** [comment]
Probably we were both using newer transformers which is why you didn't get this error.

**Comment by gitmylo** [comment]
> Probably we were both using newer transformers which is why you didn't get this error.

That's still confusing to me, as I had deleted my venv and completely reinstalled before, and still didn't have the error, weird.

**Comment by Ph0rk0z** [comment]
Well I will try to update TTS and see if it comes back.

**Comment by nekogecko2** [comment]
>it might be, try activating your virtual environment and running
>pip install git+https://github.com/coqui-ai/TTS@dev --upgrade (not entirely sure if you'll need upgrade or pip uninstall TTS and then installing the git version)

Thanks! Uninstalling TTS **first** and then running 

>pip install git+https://github.com/coqui-ai/TTS@dev" worked!

For any other complete noobs like me, you "activate venv" by drag and dropping the "activate.bat" file to command prompt from \audio-webui\venv\Scripts\activate.bat
