### ISSUE TITLE
[QUESTION]  Experiences with bark seed.

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#30]
Have you tried to use seeds with bark? https://github.com/suno-ai/bark/pull/175

Repeated generations almost never have the same voice for me and this looks to be a way to maybe have that happen. That way a good clone (in theory) could be maintained across multiple sentences and maybe even restarts of the UI.

Oh and they merged the other PR finally.

**Comment by gitmylo** [comment]
seeds probably won't help with voice cloning, but they will with having a consistent voice when all other factors are the same.

**Comment by Ph0rk0z** [comment]
Would it stop the voice from turning british or into a dude/girl?

**Comment by gitmylo** [comment]
no

**Comment by Ph0rk0z** [comment]
It's weird how this model does this or babbles nonsense after, if you continue generating. I've also had it say completely different stuff while ignoring the prompt. The larger model sometimes gives better results but it does this more often.

**Comment by gitmylo** [comment]
this may sound like a bug, but it's actually a feature for bark, the developers see it more as a generative model capable of speech and some other audio, like music, or sound effects.

**Comment by Ph0rk0z** [comment]
I suppose I want it both ways. It's cool when it does intonation and emphasizes certain things. I suppose one can't come without the other.

Guy from the PR says:To generate other prompts in sequence (long text) I set the saved seed + history_prompt for the first prompt on the list, then for the other prompts I set the saved seed + the history_prompt return by the output_full=True of the first prompt, because it helps to keep consistency. With that process the voice sounds the same and keeps the same intonation for the whole audio.


So that would imply that the clone could be made more consistent once you have the npz. The other option has been to just slice at 15s and re-generate and then combine the audio in audacity or some other DAW.

**Comment by gitmylo** [comment]
that's already how my continued generations work, it's a loopback. looping back the generated history prompt into the next generation. then at the end, pasting the audio after each other, that's why continued generations sound like a single long generation.

**Comment by Ph0rk0z** [comment]
For me only sometimes. It will often change voices on me.

**Comment by gitmylo** [comment]
in the way that bark does, i have noticed, but it rarely aligned with an actual part where they audio jumped to the next prompt. not sure then.

also, if you have multiple prompts that you want as a single long one, don't cut the prompt too short, that could cause bark to switch voices, as it does sometimes at the end of short prompts.

**Comment by Ph0rk0z** [comment]
It seems like ~15s is the best time for both samples and lines.

**Comment by gitmylo** [comment]
15 seconds is the max bark can do in a single generation after all
