### ISSUE TITLE
[QUESTION] What is filter radius?

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#32]
What does the filter radius apply to? Is lower better? is 0 off? Is higher better?

**Comment by gitmylo** [comment]
Looked into the code, it's actually unused. I should reimplement it, as it got lost when switching to a different harvest implementation.

Original RVC description claims something like `>=3, use the median filter for the result of harvest pitch recognition, and the value is the filter radius, which can weaken the mute` when translated through google translate

**Comment by Ph0rk0z** [comment]
Ahh.. I usually use torch crepe. So it was doing nothing at that point?

As for implementing.. I looked through the RVC repo and there are lots of changes. Fixes, new models, etc.

**Comment by gitmylo** [comment]
I could either hide the filter radius when not using harvest, or have it apply the filter on every mode (in which case, i'd set the default to 0 or 1, both do the same, i should probably also set the minimum to 1)

**Comment by Ph0rk0z** [comment]
So bigger filter radius is more smoothing? Or shorter?

**Comment by gitmylo** [comment]
Pitches are just a list of numbers, containing the pitch for each bit of audio.
kind of like `1, 2, 1, 3, 2, 1` (not actual numbers)
filtering it will smooth it out, so higher is more filtering, having a filter of 3 will affect the values around each value, the higher, the further it reaches with it's effects, but it also has a fall-off, like a gaussian filter, in this case, a median filter.

This can also be applied in 2d for example (example 1, from [stackoverflow](https://stackoverflow.com/questions/45316589/applying-even-sized-median-filter-in-python)):
![image](https://github.com/gitmylo/audio-webui/assets/36931363/e73e6279-92a8-42be-964e-6e8c51b8f826)

But in RVC, the filter is applied on the detected pitch values, so it will basically "blur" the pitches to be more similar, so you won't have big jumps from one pitch to the next (example 2, from [wikipedia](https://en.wikipedia.org/wiki/Median_filter#/media/File:Median_filter_example.jpg)).
![image](https://github.com/gitmylo/audio-webui/assets/36931363/57f13ce5-e6b8-4120-9209-19fb83cc35cc)

**Comment by Ph0rk0z** [comment]
Thanks, that makes sense. Probably would be good to have it in crepe too. Crepe can crack or make digital sounds but it's a bit better than harvest. Maybe smoothed harvest can now match it. The harvest voice sounds "stronger" than the crepe too.

**Comment by gitmylo** [comment]
yeah, crepe sounds slightly more like the input voice, while harvest usually sounds more like the target voice
