### ISSUE TITLE
[FEATURE REQUEST] Quality simulation for AudioLDM and maybe others

### ISSUE THREAD

**Issue by pravdomil** [gitmylo/audio-webui#36]
it is included in AudioLDM repo

maybe put it into utils tab

https://colab.research.google.com/github/olaviinha/NeuralTextToAudio/blob/main/AudioLDM_pub.ipynb

<img width="686" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/b7238fb1-2341-494f-a740-3341f26fd45a">

**Comment by gitmylo** [comment]
What does it do?

**Comment by pravdomil** [comment]
try it, it improves the audio quality a lot

**Comment by gitmylo** [comment]
Looks like it resamples to 44khz, which is higher than models usually output, and it tries to fix some of the imprecision, also looks like it applies stereo, which should sound better.

i can see why you want that, i'll add it to the utils soon.

**Comment by pravdomil** [comment]
this improves a quality a lot

```python
def main(prompt):
    pipe = diffusers.AudioLDMPipeline.from_pretrained("cvssp/audioldm-s-full-v2", torch_dtype=torch.float16).to("cuda")

    audio = pipe(prompt, num_inference_steps=10, audio_length_in_s=a.duration).audios[0]
    audio_44khz = librosa.resample(audio, orig_sr=16000, target_sr=sample_rate)
    audio_enhanced = enhance_audio(audio_44khz)

    return audio_enhanced


def enhance_audio(a: numpy.ndarray):
    octave_up = librosa.effects.pitch_shift(a, sr=sample_rate, n_steps=12, res_type="soxr_vhq")
    return a + octave_up
```

**Comment by gitmylo** [comment]
I'll try it out, i'll most likely add it in utils though, not directly in audioldm here.

**Comment by pravdomil** [comment]
put it also into `audioldm`, it is a must have, otherwise the quality is not good

**Comment by gitmylo** [comment]
I'm not sure how that code would enhance the audio, instead, it will just give it a higher pitch it seems. I'll test a bit further

**Comment by gitmylo** [comment]
Maybe that's just something with trying to use it separately.

**Comment by gitmylo** [comment]
Oh yeah, it can definitely sound better, not always though.

Prompt: Chopping carrots on a wooden plank
seed: 2919297160245668629
other options default.


https://github.com/gitmylo/audio-webui/assets/36931363/d8e684e1-0959-4c16-b650-0ea03e9f451d

https://github.com/gitmylo/audio-webui/assets/36931363/584c636d-2e26-4bc5-9c70-dbc06a772640

**Comment by pravdomil** [comment]
that sounds great, much more cleaner

**Comment by pravdomil** [comment]
great thanks!
