### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by tomas122727** [gitmylo/audio-webui#37]
**Describe the bug**
It Keeps Looping around when i try to use run.bat and

**To Reproduce**
1. it did the installs 
2. it keeps asking if my pip is up to date
3. it says no module named bark

**Expected behavior**
to run the ui

**Screenshots**

**Additional context**
Successfully installed librosa-0.10.0.post2

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement pytube...
Requirement already satisfied: pytube in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (15.0.0)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement openai-whisper...
Requirement already satisfied: openai-whisper in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (20230314)
Requirement already satisfied: more-itertools in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (9.1.0)
Requirement already satisfied: torch in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (2.0.1+cu117)
Requirement already satisfied: numpy in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (1.23.5)
Requirement already satisfied: numba in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (0.56.4)
Requirement already satisfied: ffmpeg-python==0.2.0 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (0.2.0)
Requirement already satisfied: tiktoken==0.3.1 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (0.3.1)
Requirement already satisfied: tqdm in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from openai-whisper) (4.65.0)
Requirement already satisfied: future in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from ffmpeg-python==0.2.0->openai-whisper) (0.18.3)
Requirement already satisfied: regex>=2022.1.18 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from tiktoken==0.3.1->openai-whisper) (2023.6.3)
Requirement already satisfied: requests>=2.26.0 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from tiktoken==0.3.1->openai-whisper) (2.28.1)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from numba->openai-whisper) (0.39.1)
Requirement already satisfied: setuptools in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from numba->openai-whisper) (65.5.0)
Requirement already satisfied: sympy in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from torch->openai-whisper) (1.11.1)
Requirement already satisfied: jinja2 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from torch->openai-whisper) (3.1.2)
Requirement already satisfied: networkx in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from torch->openai-whisper) (2.8.8)
Requirement already satisfied: typing-extensions in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from torch->openai-whisper) (4.4.0)
Requirement already satisfied: filelock in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from torch->openai-whisper) (3.9.0)
Requirement already satisfied: colorama in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from tqdm->openai-whisper) (0.4.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from requests>=2.26.0->tiktoken==0.3.1->openai-whisper) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from requests>=2.26.0->tiktoken==0.3.1->openai-whisper) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from requests>=2.26.0->tiktoken==0.3.1->openai-whisper) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from requests>=2.26.0->tiktoken==0.3.1->openai-whisper) (3.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from jinja2->torch->openai-whisper) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\tomas_000\desktop\audio-webui-master\venv\lib\site-packages (from sympy->torch->openai-whisper) (1.2.1)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirement git+https://github.com/facebookresearch/audiocraft.git...
Collecting git+https://github.com/facebookresearch/audiocraft.git
  Cloning https://github.com/facebookresearch/audiocraft.git to c:\users\public\documents\wondershare\creatortemp\pip-req-build-nqhxh4ny
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Preparing
Traceback (most recent call last):
  File "C:\Users\tomas_000\Desktop\audio-webui-master\main.py", line 15, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "C:\Users\tomas_000\Desktop\audio-webui-master\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "C:\Users\tomas_000\Desktop\audio-webui-master\webui\modules\implementations\ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "C:\Users\tomas_000\Desktop\audio-webui-master\webui\modules\implementations\patches\bark_custom_voices.py", line 4, in <module>
    from bark.generation import SAMPLE_RATE, load_codec_model
ModuleNotFoundError: No module named 'bark'
Press any key to continue . . .

**Comment by gitmylo** [comment]
https://git-scm.com/downloads

**Comment by tomas122727** [comment]
ok it launched also where do i go and train or clone my voice for bark ?

**Comment by tomas122727** [comment]
oh i dont want to train RVC i want to clone a voice using bark ? i saw this video this guy is doing bark ? https://youtu.be/hrYhk9Khyho

**Comment by gitmylo** [comment]
then select suno/bark on the text to speech tab

**Comment by tomas122727** [comment]
nvm i found it
