### ISSUE TITLE
[FEATURE REQUEST] Remove help accordeon add hints instead

### ISSUE THREAD

**Issue by pravdomil** [gitmylo/audio-webui#40]
just to be clear

Replace this one
<img width="612" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/05290f08-a09f-4072-8c8b-8d75fee8c3d8">

With this one for text
![image](https://github.com/gitmylo/audio-webui/assets/2387356/b03fa24f-bc52-4811-99a8-e6894ab5a848)

And this one for audio
![image](https://github.com/gitmylo/audio-webui/assets/2387356/d39dd041-76bf-4125-b6f3-f0c038564c80)

**Comment by gitmylo** [comment]
💀 okay, that's a lot of issues in one day though, i'll work on it later, i've basically been writing code non-stop today. lol

**Comment by pravdomil** [comment]
no worries take a weekend off!

you are doing great work, this can become like stable diffusion webui but for audio :D

**Comment by gitmylo** [comment]
Thanks, the goal is indeed to become like stable-diffusion-webui and text-generation-webui, but for audio.

the main problem, especially in the beginning, is that there aren't really easy huggingface pipelines for this, at all. so i had to implement my own pipelines, and because of that, the initial goal of just selecting a text to speech model and using it, didn't go very well.

luckily Coqui TTS exists, and it works basically like a pipeline for the models it supports.

**Comment by pravdomil** [comment]
you can just copy and paste the original pipelines found in the repos

and do not make it too fancy, keep it simple, each pipeline has it's own tab, even if the are doing same thing, the development goes so fast, so make your life easy


<img width="1166" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/ce99d601-7a51-438f-aa46-cb7c95ee8e9a">

**Comment by gitmylo** [comment]
> you can just copy and paste the original pipelines found in the repos
> 
> and do not make it too fancy, keep it simple, each pipeline has it's own tab, even if the are doing same thing, the development goes so fast, so make your life easy
> <img alt="image" width="1171" src="https://user-images.githubusercontent.com/2387356/248415745-6a2483f6-bce0-429f-ae58-6a22559dbb49.png">

that's not what i meant by pipelines, i meant a "one size fits all" pipeline, like the transformers and diffusers pipelines.

In this case, only bark/coqui use a single pipeline, the rest has it's own pipeline

**Comment by gitmylo** [comment]
The accordion will stay though, it wouldn't look good if there was a whole chunk of info. i might add global javascript code though, which can be used to tag things, and show better hints for example when you hover over the element.

**Comment by pravdomil** [comment]
> the main problem, especially in the beginning, is that there aren't really easy huggingface pipelines for this, at all.

https://github.com/huggingface/transformers/releases/tag/v4.31.0

**Comment by gitmylo** [comment]
Yeah, looks like they're working on it. It's not a single universal pipeline though, so having them as separate modules is still the best way to go.
