### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by nmeftah** [gitmylo/audio-webui#43]
**Describe the bug**
syntax error when running install.bat on windows on line 1"@echo off"

**To Reproduce**
1. python install.bat

**Expected behavior**
expected to install the software

**Comment by gitmylo** [comment]
don't use the python command to run a batch file. you run it by double clicking the file or typing `install.bat` in cmd.

**Comment by nmeftah** [comment]
when running the batch file correctly now i now get an error saying "no suitable python runtime found"

**Comment by nmeftah** [comment]
when running py it correctly launches the python interface, it does say version 3.11.4 though, does the file only work on 3.10?

**Comment by gitmylo** [comment]
yeah, only python 3.10 is supported at the moment, as the TTS library does not support newer versions yet

**Comment by nmeftah** [comment]
ok got it thank you!

**Comment by gitmylo** [comment]
Are you sure you're running with python 3.10 then?

**Comment by nmeftah** [comment]
fairly positive, i uninstalled 3.11 before installing 3.10

**Comment by gitmylo** [comment]
Uninstalling python is usually a bad idea, but send the console output. it should show your python version as like the first thing.

i will be inactive for a bit though, it's getting late here.

**Comment by nmeftah** [comment]
says its running 3.10.11

**Comment by nmeftah** [comment]
<img width="653" alt="Screenshot 2023-06-26 132432" src="https://github.com/gitmylo/audio-webui/assets/137450457/d5caa957-ea2d-4ca0-a463-6fb448cbbf21">


heres the screenshot

**Comment by gitmylo** [comment]
## Try this:

1. open a cmd in the webui's directory
2. run `venv\Scripts\activate.bat`
3. it should now show "(venv)" at the start of your cmd input
4. run `pip install TTS`
5. if this fails to install, delete your venv folder, and run install again. as that would mean the venv was using the wrong python version

**Comment by nmeftah** [comment]
sounds good, ill let ya get some rest now lol

**Comment by nmeftah** [comment]
i gave what you said a try and when i tried reinstalling i noticed a message saying "could not build wheels for TTS" along with a recommendation to update my pip. let me know what you think once youre awake again

**Comment by gitmylo** [comment]
i'd need the full error message to know what failed when building wheels

usually it's because you don't have visual studio c++ build tools installed.

**Comment by nmeftah** [comment]
<img width="856" alt="Screenshot 2023-06-27 162250" src="https://github.com/gitmylo/audio-webui/assets/137450457/3c912b2f-fa67-4939-840c-296e0fb3106a">


heres the full error message when running pip to install TTS

**Comment by gitmylo** [comment]
Yeah, you need visual studio build tools.

follow the link in that error message, and download the build tools.

**Comment by nmeftah** [comment]
<img width="855" alt="Screenshot 2023-06-27 170224" src="https://github.com/gitmylo/audio-webui/assets/137450457/fbd51138-7322-435a-aff0-938c302917db">

**Comment by nmeftah** [comment]
any idea how to fix this error?

**Comment by nmeftah** [comment]
im also seeing a lot of errors regarding pips dependency resolver if you have any insights into that

**Comment by gitmylo** [comment]
Not sure, maybe you could find more info on it by searching for the error message, although i'm not sure which part of the error message shows the issue. I've never seen this error before, at least that i remember.

The errors with pip's dependency resolver are because every package is installed separately, since i use a custom format for installing the packages.

**Comment by nmeftah** [comment]
so the dependency error i shouldnt worry about?

**Comment by nmeftah** [comment]
<img width="917" alt="Screenshot 2023-06-27 171920" src="https://github.com/gitmylo/audio-webui/assets/137450457/05e2d28a-d532-4f4b-b90a-02aed9ecca74">


this is another modulenot found error i didnt have much luck finding answers for online

**Comment by gitmylo** [comment]
> so the dependency error i shouldnt worry about?

Yeah, that's not really something to worry about.



> <img alt="Screenshot 2023-06-27 171920" width="917" src="https://user-images.githubusercontent.com/137450457/249232599-05e2d28a-d532-4f4b-b90a-02aed9ecca74.png">
> 
> this is another modulenot found error i didnt have much luck finding answers for online

This is probably because of the error you sent above, it failed to install.

You can alternatively try installing scikit_learn manually. And then once that's done, run the install.bat again.
To install scikit_learn manually:
1. run `activate_only.bat` (if it's not in your audio-webui folder, update to the latest version)
2. from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-learn) download `scikit_learn‑1.1.1‑cp310‑cp310‑win_amd64.whl` or `scikit_learn‑1.1.1‑cp310‑cp310‑win32.whl` (amd64 if you have a 64-bit cpu, win32 if you have a 32-bit cpu. You probably want amd64, as most cpus nowadays are 64-bits)
3. in the cmd window from step 1, run `pip install [filename]` where `[filename]` is the path to the file that you downloaded on step 2.

**Comment by nmeftah** [comment]
alright, let me see how that goes

**Comment by nmeftah** [comment]
after installing the scikit manually i still get the same modulenotfound error when running

**Comment by gitmylo** [comment]
did you also re-run install.bat? since that's important if you installed scikit manually.

**Comment by nmeftah** [comment]
yes i did

**Comment by gitmylo** [comment]
What was the error in the console during install now?

**Comment by nmeftah** [comment]
there was no install error, there an error when running the run.bat file which was the same as the screenshot i attached above saying no module named audiolm_pytorch

**Comment by gitmylo** [comment]
Can you try opening the `activate_only.bat` again, and running `pip install audiolm-pytorch`?
I will see if i can improve the automatic installers in the future. So it knows by itsself where the install failed, and so it can suggest a solution.

**Comment by nmeftah** [comment]
just tried this and now in the venv it says failed building wheel for scikit-learn again

**Comment by gitmylo** [comment]
odd, i don't think that should happen if you already have it installed from the steps before. Are you sure you installed it in your virtual environment? (aka, it says "`(venv)`" before the command prompt input)

**Comment by nmeftah** [comment]
almost certain i did

**Comment by nmeftah** [comment]
is there any way to check?

**Comment by gitmylo** [comment]
Inside of the venv, run `pip freeze`, and look for scikit-learn. It should show the version which is installed.

**Comment by nmeftah** [comment]
shows scikit-learn with the path i copied leading to the downloaded file

**Comment by gitmylo** [comment]
I don't know why it isn't working then. Back to the issue from before then. Something's wrong which is causing it to be unable to install scikit-learn.

Assuming `pip install scikit-learn` gives the same error. Maybe try `pip install scipy` and then `pip install scikit-learn`

**Comment by nmeftah** [comment]
let me give that a try

**Comment by nmeftah** [comment]
says they are both already satisfied

**Comment by nmeftah** [comment]
sounds good, thank you

**Comment by gitmylo** [comment]
It passed the wheel building, so i don't know what's going on for you. Try it on another machine. Or alternatively, use the google colab.

**Comment by nmeftah** [comment]
ill try a clean install as well and see if it works

**Comment by nmeftah** [comment]
when redoing the install the only thing failing is the scikit-learn and when i check the installed packages it still says scikit is installed as version 1.2.2 and scipy is version 1.11.0

**Comment by gitmylo** [comment]
That's really odd. I couldn't find anything on the internet about that bug though. Sorry.

**Comment by nmeftah** [comment]
strange, guess ill try it on another machine and see what happens

**Comment by nmeftah** [comment]
and one last question, how would i run the install from linux?

**Comment by gitmylo** [comment]
Wherever you'd normally do something with `.bat`, you now use the `.sh` variants

**Comment by gitmylo** [comment]
do you have python 3.10 installed?

**Comment by nmeftah** [comment]
yeah its 3.10.6

**Comment by gitmylo** [comment]
what happens when you try to run `python3.10` as a command?

**Comment by nmeftah** [comment]
it launches python

**Comment by gitmylo** [comment]
I have changed the check to use "which", can you git pull the changes and check if it works now?

**Comment by nmeftah** [comment]
still nothing

**Comment by gitmylo** [comment]
nothing? can you show the output?

**Comment by nmeftah** [comment]
![Screenshot from 2023-06-27 12-09-07](https://github.com/gitmylo/audio-webui/assets/137450457/bce34172-655c-4599-82e1-908e8e804298)

**Comment by gitmylo** [comment]
oh, that.

In linux bash, to run a script. you start with "./". So in this case, the correct command is "`./install.sh`"

**Comment by nmeftah** [comment]
ahhh ok, sorry, i haven't used linux too much before

**Comment by nmeftah** [comment]
so now when i run it i get a message saying permission denied

**Comment by gitmylo** [comment]
try `sudo ./[file]`.
if that fails, try `chmod +rwx [file]`, and then running the file again

**Comment by nmeftah** [comment]
works now but now theres this error
![Screenshot from 2023-06-27 12-16-04](https://github.com/gitmylo/audio-webui/assets/137450457/6dacf10a-1c33-4286-a4fd-2925618dba44)

**Comment by gitmylo** [comment]
delete the venv folder, windows venvs are structured differently from linux venvs.

windows venv's activate: `venv\Scripts\activate.bat`
linux/macos venv's activate: `venv/bin/activate`

**Comment by nmeftah** [comment]
ok got it, working now

**Comment by nmeftah** [comment]
so when i run the run file it worked perfectly until this point
![Screenshot from 2023-06-27 12-32-10](https://github.com/gitmylo/audio-webui/assets/137450457/64dfa7fd-d127-4d26-8fec-29a40bb6f55b)

**Comment by nmeftah** [comment]
now its just stuck at that point

**Comment by gitmylo** [comment]
yeah, just open the link in your browser (http://127.0.0.1:7860)

**Comment by nmeftah** [comment]
ah ok i see

**Comment by nmeftah** [comment]
linux worked perfectly, im now trying to get it to run on macos but im getting a message saying i need visual build tools for c++ but if i recall correctly that not compatible on mac

**Comment by gitmylo** [comment]
that's weird, pretty sure on macos you'd need a compiler like gcc

https://stackoverflow.com/questions/59977457/installing-gcc-on-macos-catalina

**Comment by nmeftah** [comment]
let me give that a shot

**Comment by nmeftah** [comment]
so after installing the gcc I still get an error saying theres no module named TTS

**Comment by gitmylo** [comment]
did you check if it installed correctly this time?

**Comment by nmeftah** [comment]
when i look through  the install no errors come up but hwne i check the package list in the venv theres nothing about TTS so when i tried to manually install that i get an error saying no such file or directory: 'mecab-config'

**Comment by gitmylo** [comment]
`pip install mecab` might help. Not really sure though.
