### ISSUE TITLE
No --listen parameter

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#5]
I run this stuff over the network off a server and am not able to access the web UI over my local network. A public instance is not ideal for me to go out of my lan and back again.

**Comment by melMass** [comment]
What do you mean?
By default it's not exposed to LAN, you can expose it to LAN. And if you want to connect from outside that's a firewall + router/ISP thing

**Comment by gitmylo** [comment]
I'll add a --listen flag

**Comment by Ph0rk0z** [comment]
thanks
