### ISSUE TITLE
[BUG REPORT]  Extraction failed, each element of kernel_size should be false

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#53]
**Describe the bug**

New crepe works for inference but fails to extract all pitches for training. Message in webui is as title.

**To Reproduce**
extract pitches with mangio-crepe

**Additional context**
1_feat are created, others are not.

**Comment by gitmylo** [comment]
I'll check it out soon

**Comment by gitmylo** [comment]
I cannot reproduce the issue, as it works for me. Does it still happen when you try to extract pitches with mangio-crepe? If so, can you send the whole error message?

![image](https://github.com/gitmylo/audio-webui/assets/36931363/23823b24-7d6f-496a-a480-40dd7ea6eada)

**Comment by Ph0rk0z** [comment]
I will check again today.

**Comment by Ph0rk0z** [comment]
I think I know why this happened.. mangio-crepe doesn't accept even filter sizes and I had set mine to 4. 
1, 3, 5 all work.

**Comment by gitmylo** [comment]
> I think I know why this happened.. mangio-crepe doesn't accept even filter sizes and I had set mine to 4. 1, 3, 5 all work.

oh, right, makes me wonder, does any model support even filter sizes? in that case, i should change the meaning of the filter a little bit, so 1 stays 1, 2 becomes 3, 3 becomes 5, etc. Since i don't think you can have an offset slider.

**Comment by Ph0rk0z** [comment]
I used filter sizes like 4 for the regular crepe, at least for inference.
