### ISSUE TITLE
[BUG REPORT] ConnectionResetError

### ISSUE THREAD

**Issue by patrickmac110** [gitmylo/audio-webui#56]
**Describe the bug**
When generating audio with bark, after it goes through and gets to the final stages of generation, it'll sucesfully complete (I believe) and give me an audio file that sounds fine as far as I can tell, however there's typically some errors that're thrown in the cmd window as well and I just wanted to make you aware of them at the very least, and make sure they weren't causing other issues as well.

Generation split into sections: ['[woman] "I can\'t believe you did this to me!" [man] Alice shouted, throwing the vase at Bob\'s head. He ducked and ran out of the door, leaving her alone with the broken pieces of their marriage.', ' [woman] [whispering] "Don\'t go, please," [man] she whispered, collapsing on the floor in tears. Bob didn’t say anything. He was too afraid of Alice’s anger and hurt. He knew he had made a terrible mistake,', ' but he didn’t know how to fix it. He just wanted to get away from the scene of his betrayal.']
ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, png_pipe, from 'C:\Users\Patrick\AppData\Local\Temp\tmpg12s0oww.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc), 1000x200, 25 fps, 25 tbr, 25 tbn
Guessed Channel Layout for Input Stream #1.0 : mono
Input #1, wav, from 'C:\Users\Patrick\AppData\Local\Temp\tmpmckuvh0q.wav':
  Duration: 00:00:38.92, bitrate: 384 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, mono, s16, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0000000000ef7000] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000000000ef7000] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0000000000ef7000] 264 - core 164 r3099 e067ab0 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\Patrick\AppData\Local\Temp\tmp3n0lbnii.mp4':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1000x200, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.37.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 24000 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc59.37.100 aac
frame=  973 fps=793 q=-1.0 Lsize=     473kB time=00:00:38.95 bitrate=  99.4kbits/s speed=31.7x
video:82kB audio:366kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 5.534837%
[libx264 @ 0000000000ef7000] frame I:4     Avg QP:12.78  size:  5977
[libx264 @ 0000000000ef7000] frame P:301   Avg QP:20.67  size:   119
[libx264 @ 0000000000ef7000] frame B:668   Avg QP:16.30  size:    35
[libx264 @ 0000000000ef7000] consecutive B-frames:  1.0% 20.6%  5.2% 73.2%
[libx264 @ 0000000000ef7000] mb I  I16..4: 75.5%  5.9% 18.6%
[libx264 @ 0000000000ef7000] mb P  I16..4:  0.9%  0.5%  0.0%  P16..4:  3.8%  0.2%  0.1%  0.0%  0.0%    skip:94.6%
[libx264 @ 0000000000ef7000] mb B  I16..4:  0.1%  0.0%  0.0%  B16..8:  1.6%  0.1%  0.0%  direct: 0.0%  skip:98.2%  L0:45.7% L1:54.1% BI: 0.2%
[libx264 @ 0000000000ef7000] 8x8 transform intra:19.8% inter:38.3%
[libx264 @ 0000000000ef7000] coded y,uvDC,uvAC intra: 4.8% 12.4% 10.5% inter: 0.0% 0.1% 0.0%
[libx264 @ 0000000000ef7000] i16 v,h,dc,p: 94%  2%  5%  0%
[libx264 @ 0000000000ef7000] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  8%  1% 90%  1%  0%  0%  0%  0%  0%
[libx264 @ 0000000000ef7000] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 61% 17% 17%  0%  1%  1%  1%  1%  1%
[libx264 @ 0000000000ef7000] i8c dc,h,v,p: 39%  5% 55%  0%
[libx264 @ 0000000000ef7000] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0000000000ef7000] ref P L0: 95.9%  0.2%  3.1%  0.8%
[libx264 @ 0000000000ef7000] ref B L0: 76.2% 22.1%  1.6%
[libx264 @ 0000000000ef7000] ref B L1: 99.5%  0.5%
[libx264 @ 0000000000ef7000] kb/s:17.14
[aac @ 0000000002aff900] Qavg: 1151.147
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by gitmylo** [comment]
this connectionerror is a user-related issue. it can usually be ignored, as it automatically reconnects. It basically just means that your browser lost connection to the webui for a bit.

**Comment by melMass** [comment]
Yep I'm seing this in all gradio based projects, it can safely be ignored
