### ISSUE TITLE
[FEATURE REQUEST] Combine development efforts with tts-generation-webui

### ISSUE THREAD

**Issue by underlines** [gitmylo/audio-webui#59]
You might or might not be aware of [rsxdalv/tts-generation-webui](https://github.com/rsxdalv/tts-generation-webui) which has very similar goals. Maybe it would make sense to combine forces with rsxdalv?

**Comment by Ph0rk0z** [comment]
That repo only has vocos (never tried) and tortoise (has MRQ ai voice cloning UI). Maybe it's worth it to implement vocos tho: https://charactr-platform.github.io/vocos/

**Comment by gitmylo** [comment]
Yeah, vocos is indeed something i have thought about implementing.
I will also make some contributions to the bark implementation in the [🐸 TTS](https://github.com/coqui-ai/TTS) library and you can expect to see those changes to also be made to the bark implementation in audio-webui.

Also expect some frankenstein Bark features which might be pretty cool too. They should speed up inference but with a twist. Mainly looking at the coarse model here though. The possibilities are endless.

**Comment by Ph0rk0z** [comment]
I tried the PRs in the bark queue and got a speedup for at least the first step. Bark only seems to use 30% gpu so I wonder if there is a bottleneck.

**Comment by Ph0rk0z** [comment]
I think this is what was meant by people mentioning bark V2: https://github.com/suno-ai/bark/compare/main...dev

Is it just bark with history prompt or something else done to the NPZ?

**Comment by Ph0rk0z** [comment]
That make sense. They just left the dev branch.
