### ISSUE TITLE
[BUG REPORT] Selecting "small" in settings appears to d/l the large models.

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#60]
Cloning is hitting different so I decided to try the small models again. When I select small models after using large I get an index error. When I do it on a fresh start it tries to download coarse_2.pt and text_2.pt, etc even though they're already moved to the suno folder in audio-webui models directory (and are the large models?).

Also will it be possible to mix and match small text + large coarse + small fine, etc.

**Comment by gitmylo** [comment]
I thought i had pushed the fix, i guess it got lost somewhere, maybe i rollbacked the fix. I'll push it again.

Yes, mixing models is possible, that's why you are able to pick each model.

I recommend always using large fine though, it's so much better and basically instant anyways.

**Comment by gitmylo** [comment]
I had definitely pushed this, i have no idea where the code went, so i'll rewrite that...

**Comment by Ph0rk0z** [comment]
Sometimes stuff gets lost with GH. But what I noticed was that bark gens are now louder and have more reverb. Almost like they got normalized.

**Comment by gitmylo** [comment]
> Sometimes stuff gets lost with GH. But what I noticed was that bark gens are now louder and have more reverb. Almost like they got normalized.

Are you using the small fine model? I recommend always using the large fine model, as i've heard bad things about the small fine model.

**Comment by Ph0rk0z** [comment]
No.. I only use the large models. I was wanting to try the small ones because I noticed something was different. After I updated I did notice a new hubert download I think. Only other difference I can think of.

**Comment by Ph0rk0z** [comment]
Yea.. I dunno what exactly did it. Just noticed that the same npz and wav files produced much more reverb-y gens. Is the quantizer only used during generation of the NPZ or always.

**Comment by gitmylo** [comment]
> Yea.. I dunno what exactly did it. Just noticed that the same npz and wav files produced much more reverb-y gens. Is the quantizer only used during generation of the NPZ or always.

The quantizer is only used during cloning. Nothing has changed with the quantizer.
