### ISSUE TITLE
[QUESTION] NPZ not sounding the same in recent version?

### ISSUE THREAD

**Issue by melMass** [gitmylo/audio-webui#62]
# NPZ not sounding the same in recent version?

Hi,

I just pulled the changes but now every single generation sound like a very high pitched woman with an npz voice of a man that worked really well before, did something changed?

Thanks

**Comment by gitmylo** [comment]
Hmm, this seems similar to what was mentioned in https://github.com/gitmylo/audio-webui/issues/60#issuecomment-1621956487
Not sure what it is. I'll check if any libraries updated that might have caused, and i'll verison lock the one which caused this issue.

**Comment by gitmylo** [comment]
It appears to be working normally for me. It might be your prompt here. I have had it use a different voice than my speaker npz before because some prompts make bark use a different voice.

**Comment by melMass** [comment]
Thanks I'll dig more and try to regenerate the NPZs in the new version since I kept all the input samples

**Comment by gitmylo** [comment]
> Thanks I'll dig more and try to regenerate the NPZs in the new version since I kept all the input samples

Nothing has changed though

**Comment by Ph0rk0z** [comment]
Regenerating NPZ for me at least didn't make a difference. NPZ comes out the same exact size too.

**Comment by gitmylo** [comment]
Can you confirm this is still an issue? As i haven't noticed anything related to this changing myself, and i haven't really touched the code at all.

**Comment by melMass** [comment]
Then I think it might be my fault. As in I had issues at first and made edits to the code locally... but reset pulled to get all the recent stuff like RVC I'll reopen if needed 
Thanks!
