### ISSUE TITLE
ubuntu18.04  bash ./run.sh     have error  

### ISSUE THREAD

**Issue by yuhao910716** [gitmylo/audio-webui#63]
(audio-webui) yuhao@yuhao-System-Product-Name:~/bark-yh-data/audio-webui$ bash ./run.sh
Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Failed to install bark. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting git+https://github.com/suno-ai/bark.git@6921c9139a97d0364208407191c92ec265ef6759
  Cloning https://github.com/suno-ai/bark.git (to revision 6921c9139a97d0364208407191c92ec265ef6759) to /tmp/pip-req-build-e5yucz9l
  Resolved https://github.com/suno-ai/bark.git to commit 6921c9139a97d0364208407191c92ec265ef6759
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'

STDERR:
  Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git /tmp/pip-req-build-e5yucz9l
  Running command git rev-parse -q --verify 'sha^6921c9139a97d0364208407191c92ec265ef6759'
  Running command git fetch -q https://github.com/suno-ai/bark.git 6921c9139a97d0364208407191c92ec265ef6759
  Running command git checkout -q 6921c9139a97d0364208407191c92ec265ef6759
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
      ERROR: No matching distribution found for setuptools
      
      [notice] A new release of pip is available: 23.0.1 -> 23.1.2
      [notice] To update, run: pip install --upgrade pip
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

Please read the error above carefully. 
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 1

**Comment by gitmylo** [comment]
Can you reach https://pypi.tuna.tsinghua.edu.cn/ ? It seems to be unable to reach this address. Which it is trying to download setuptools from.

I can access it myself, so it's definitely online. Does it show anything when you go to the webpage? Maybe access denied, or an ISP block message?

**Comment by gitmylo** [comment]
the install-requirements.txt is in a custom format, also, it is no longer used, because it has been replaced by the safer "magicinstaller" system, which can check versions and compare, so it's also faster.

**Comment by gitmylo** [comment]
I will be closing this issue, if you still have issues, just send another message in this issue. I'll see them even if it's closed.

**Comment by yuhao910716** [comment]
@gitmylo thankyou
