### ISSUE TITLE
[FEATURE REQUEST] more descriptive tags for the buttons and an audioldm feature

### ISSUE THREAD

**Issue by audioses** [gitmylo/audio-webui#65]
Hello, I am visually impaired and some of the tags on the buttons confuses me. For example from what I can remember, there is a button with a rocket emoji, a generate button, and another emoji which I cant remember. Can there be additional texts be added to make it more understandable? Because I could not found a manual  which explained these buttons.
For the audioldm request, I believe audioldm can also take an audio as an input. Is it possible to make it so it can get both text and audio as input as well? Thank you very much!

**Comment by gitmylo** [comment]
Yes, audioLDM does support audio as input.

The rocket emoji loads a model, the bomb emoji unloads a model.

I will see if i can add some javascript code to add tooltips, as gradio does not support them out of the box.

**Comment by audioses** [comment]
oh that is great to know thank you. Does that mean audio WebUI support input or, the app supports it but the webUI currently does not support it yet? I am slightly confused there :) Because yesturday I've tried to see if it is available, and found no way to use an audio

**Comment by gitmylo** [comment]
AudioLDM itsself supports audio as input, so adding it won't take very long! It's not in audio-webui currently though. But i'll add it soon, along with tooltips for buttons. (mainly word descriptions for emoji buttons for now)

**Comment by audioses** [comment]
thank you very much! I will be looking forward to it. Cheers💯

**Comment by madwurmz** [comment]
ha yes the emojis are fun, probably inspired by huggingface gradio, 🤗 but it would be real nice if it would use some more professional and clear icons and labels. The rocket is also used on Workspaces, kind of confusing.🚀

Stable diffusion uses tooltips with some code in hints.js, maybe interesting.

**Comment by gitmylo** [comment]
> ha yes the emojis are fun, probably inspired by huggingface gradio, hugs but it would be real nice if it would use some more professional and clear icons and labels. The rocket is also used on Workspaces, kind of confusing.rocket
> 
> Stable diffusion uses tooltips with some code in hints.js, maybe interesting.

yeah, hints.js was the main reason i added js loading support. So now i just have to add it. Module scripts are supported too so i can just have it load it from the main script.

**Comment by gitmylo** [comment]
I will close the issue, but i will make sure to avoid things being too unclear in future commits.
