### ISSUE TITLE
[BUG REPORT] Audiocraft doesn't work

### ISSUE THREAD

**Issue by perkel666** [gitmylo/audio-webui#66]
**Describe the bug**
Default installation with no changes to settings. I type 'smooth jazz at beach' I click generate and nothing. IT doesn't do anything at all. No error, no nothing.

**Expected behavior**
It should generate music.

**Comment by gitmylo** [comment]
Do you have a model loaded? Press the rocket button to load a model, and bomb to unload.

**Comment by perkel666** [comment]
> Do you have a model loaded? Press the rocket button to load a model, and bomb to unload.

Nope did not have it loaded. Didn't know rocket loaded it as there was no tooltip and wiki isn't showing how to use audiocraft.

**Comment by gitmylo** [comment]
Yeah, i will add an error message, a lot of the ui on the audiocraft tab is copied from the audioldm tab, but the textbox was removed so it won't show that message.

**Comment by gitmylo** [comment]
New error message.

![image](https://github.com/gitmylo/audio-webui/assets/36931363/3a28615b-cb82-4c42-8271-d93ccbaabb8d)

**Comment by perkel666** [comment]
yeah but there should be at least toolbox on those rockets and bombs. Otherwise i wouldn't even know where to load model. I would search folders or something.

Or even better make so that picking model loads model on generation. So user doesn't need to manually load it. It will stay using model unless you change tool or model.

**Comment by gitmylo** [comment]
> yeah but there should be at least toolbox on those rockets and bombs. Otherwise i wouldn't even know where to load model. I would search folders or something.
> 
> Or even better make so that picking model loads model on generation. So user doesn't need to manually load it. It will stay using model unless you change tool or model.

this has been updated as well, hovering over emoji buttons now gives a tooltip!
