### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by GayGod** [gitmylo/audio-webui#67]
STDERR:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Owner\\Desktop\\07\\audio-webui\\venv\\Lib\\site-packages\\~umpy\\.libs\\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Check the permissions.

after running run.bat on Windows11

**Comment by gitmylo** [comment]
try re-running

**Comment by GayGod** [comment]
i get the same error over

**Comment by gitmylo** [comment]
Can you send me the log?

**Comment by GayGod** [comment]
nvm it fixed, but now how do i select an rvc to use?

**Comment by gitmylo** [comment]
Drop RVC models into `data/models/rvc`, press the refresh button and they'll show up.

You could also train an RVC model yourself on the train tab. Do not use 48k, they don't work yet.

**Comment by GayGod** [comment]
![image](https://github.com/gitmylo/audio-webui/assets/75827838/2970c3d1-6095-4293-9246-1a40a717a84f)
![image](https://github.com/gitmylo/audio-webui/assets/75827838/a27b49fe-c594-421d-a7d9-c50fffaea2c8)
i pu them there still no workie

**Comment by gitmylo** [comment]
It needs to be in a subdirectory, also, include the .index file with it.
The reason it needs to be in a subdirectory is so it knows if there's an index file, and which one is the correct one.

**Comment by GayGod** [comment]
can it do real time conversion?

**Comment by GayGod** [comment]
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Owner\Desktop\07\audio-webui\webui\ui\tabs\rvc.py", line 81, in gen
    sr, audio_in = audio_in
TypeError: cannot unpack non-iterable NoneType object

**Comment by gitmylo** [comment]
> can it do real time conversion?

not yet, that's what the https://github.com/gitmylo/audio-webui/tree/real-time-rvc branch is for, but i haven't worked on it enough yet. it's a planned feature.

**Comment by gitmylo** [comment]
> Traceback (most recent call last): File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict output = await app.get_blocks().process_api( File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api result = await self.call_function( File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function prediction = await anyio.to_thread.run_sync( File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 807, in run result = context.run(func, *args) File "C:\Users\Owner\Desktop\07\audio-webui\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper response = f(*args, **kwargs) File "C:\Users\Owner\Desktop\07\audio-webui\webui\ui\tabs\rvc.py", line 81, in gen sr, audio_in = audio_in TypeError: cannot unpack non-iterable NoneType object

This error happens if you
a: don't have an input audio file
or
b: don't have a model selected
