### ISSUE TITLE
Issues with Fairseq 

### ISSUE THREAD

**Issue by NekoChan704** [gitmylo/audio-webui#71]
I can't run audio-webui, when I run "run.bat" i get a ERROR message : 
""
ERROR: Failed building wheel for fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects ""

I try to install fairseq with the "activate_only.bat" but I don't think it's working.

I'm using windows 10 with python 3.10

I can give some more details to help, if you need it.

**Comment by gitmylo** [comment]
Try installing this and trying again

https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

**Comment by NekoChan704** [comment]
I try installing Windows SDK but it doesn't seems to work, i get the same error. I don't know what's not working for me. 
Maybe it can be a problem with fairseq ?

**Comment by gitmylo** [comment]
It's probably not an issue with fairseq, as most users don't get this error. It's usually that something is missing in your system, such as the windows SDK.

I'll need a longer log to see what the exact problem is, though.

**Comment by NekoChan704** [comment]
the Discord server, help me. 
It's fine now.

**Comment by transitgrave** [comment]
I also had this error and installing the Windows SDK fixed it.
