### ISSUE TITLE
Windows 11: [!] No espeak backend found. Install espeak-ng or espeak to your system.

### ISSUE THREAD

**Issue by orangpelupa** [gitmylo/audio-webui#73]
using coloqui model, and vctk/vits

error [!] No espeak backend found. Install espeak-ng or espeak to your system.

but in the docs, no instruction how to install espeak.

i've installed espeak using the espeak installer from https://espeak.sourceforge.net/download.html and still the exact same error

**Comment by gitmylo** [comment]
Not related to audio-webui. Try asking in the coqui TTS repository. I personally wasn't able to get it working on windows either, and I have not tried on linux either.

https://github.com/coqui-ai/TTS
