### ISSUE TITLE
[BUG REPORT] Memory leak / out of memory error

### ISSUE THREAD

**Issue by jh-792** [gitmylo/audio-webui#74]
When generating text to speech using Bark, memory never seems to be freed up.

After 20-30 generations (whether in a single long chunk of text that gets split up, or as many individual generations) my 32GB of memory has been gobbled up causing the system to lock up.

Unloading Bark and reloading the model doesn't free up the memory, the only way to free up the memory seems to be to close and reload audio-webui.

I'm running Ubuntu 22.04.

**Comment by gitmylo** [comment]
That's odd, i've been able to perform at least 50 generations on bark, i have 48gb ram, and am running Kubuntu 23.04. I'll see if i have missed this maybe.

**Comment by gitmylo** [comment]
![image](https://github.com/gitmylo/audio-webui/assets/36931363/1591e219-c357-4ba6-b2da-e01c4df681a9)

Yeah there appears to be a memory leak, i'll tell the bark devs about this. (Closing this issue as it appears related to bark)

**Comment by gitmylo** [comment]
It could also be an issue with gradio, maybe
