### ISSUE TITLE
[QUESTION] How Bark is being trained?

### ISSUE THREAD

**Issue by alexander-rakhlin** [gitmylo/audio-webui#76]
Is there general understanding how to train Bark itself?

**Comment by gitmylo** [comment]
Not in audio-webui.

I believe https://github.com/serp-ai/bark-with-voice-clone recently implemented fine-tuning of bark based on [HuBERT quantizer](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer) tokens.

This has not been implemented into audio-webui, as i haven't heard such great outputs as i was hoping for yet, and i'm working on something else to add, which might sound better.
