### ISSUE TITLE
[BUG REPORT] Unable to run RVC

### ISSUE THREAD

**Issue by labx12** [gitmylo/audio-webui#79]
**Describe the bug**
When attempting to run RVC on an input file, in this case, a sub 10 second .wav file, a bunch of traceback errors are thrown in the console and I'm not entirely sure what the issue would be. 

**To Reproduce**
After loading RVC model, try to run the model on an input. 

**Expected behavior**
Supposed to process the audio as expected, but throws a bunch of traceback errors instead. 

**Screenshots**
Attached a .txt w/ the error (it's 140 lines.)
[audio-webui error log.txt](https://github.com/gitmylo/audio-webui/files/12098048/audio-webui.error.log.txt)

**Comment by gitmylo** [comment]
Send a screenshot of your settings. Also, did you wait for the file to finish uploading? (this is indicated by being able to preview the audio in the editor)

**Comment by gitmylo** [comment]
I'm going to close this issue due to inactivity.
