### ISSUE TITLE
[BUG REPORT] rmvpe re-downloads the "rmvpe.pt" model everytime it's run

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#83]
rmvpe doesn't work through the training pitch extract section because it gets stuck in a permanent `Downloading rmvpe.pt -> Loading rmvpe.pt model ` loop

rmvpe works in the RVC audio input section but always re-downloads the rmvpe.pt model everytime

**Comment by gitmylo** [comment]
I made the wrong assumption that huggingface hub wouldn't redownload the file with the settings i gave it, i'll check if the file exists before downloading in the future, i already have a fix locally, just testing it now
