### ISSUE TITLE
[BUG REPORT] Exception Failed to load audio: [WinError 2] The system cannot find the file specified Skipping

### ISSUE THREAD

**Issue by TheKingGamer117** [gitmylo/audio-webui#89]
**Describe the bug**
When trying to resample and split dataset after directly copying and pasting dataset path the error: "Exception Failed to load audio: [WinError 2] The system cannot find the file specified Skipping" seems to happen and will not see any audio files with in the folder. 

**To Reproduce**
Copy and paste audio files path from windows explorer to dataset path

**Expected behavior**
Should see the audio files and load them to be used for training

**Screenshots**
![image](https://github.com/gitmylo/audio-webui/assets/91400745/36879534-7e27-4737-a1dc-9d5f99abd0c2)

**Comment by gitmylo** [comment]
Do you have ffmpeg installed?

**Comment by TheKingGamer117** [comment]
Yes ffmpeg is installed on system and the path is set

**Comment by gitmylo** [comment]
it uses ffmpeg to load the audio but that message indicates that the command was not found, you could try converting the audios to wav using the ffmpeg utils' anything to wav converter

**Comment by TheKingGamer117** [comment]
So I did try this before using audacity and even used 22050 Hz as a base
frequency when exporting and still get the error message. So I used both
wave and mp3 22050 Hz.

**Comment by gitmylo** [comment]
If you're still having this issue, please reopen the issue, if not. You don't have to do anything.
