### ISSUE TITLE
Longer bark generations in some way.

### ISSUE THREAD

**Issue by Ph0rk0z** [gitmylo/audio-webui#9]
I put in text in the box but only 14s will generate. I know there was some limit on this in the official bark but maybe it's possible to generate again and concatenate the files. It can't get past the first sentence of the vaporeon copypasta.

**Comment by gitmylo** [comment]
right, this is planned, but i haven't taken the time to implement it yet. i'm hoping to implement it with something better than sentence splitting, maybe. the semantic model is limited, but the coarse and fine audio are fine with longer audio

**Comment by gitmylo** [comment]
aw man all of those changes show up

**Comment by Ph0rk0z** [comment]
That's github for you.

**Comment by oliverban** [comment]
There is something called Bark Infinity, or something like that?

**Comment by gitmylo** [comment]
Added long form generations, didn't really have text, so i just told it to generate 4 chunks of 15 seconds (bark's original limit) with random words (no early stopping). As you can hear in the clip, the voice stays consistent, even though this is a randomly generated voice, not a speaker .npz file.

https://github.com/gitmylo/audio-webui/assets/36931363/216efb37-3f8e-4286-84a8-10d18c2846cf

This is done by loopback of the generated audios.

**Comment by Ph0rk0z** [comment]
Nice, I can try this as TTS for RVC vs other ones.

**Comment by gitmylo** [comment]
I have added a button to send generated audio from the text to speech tab to RVC, i might make some other changes to clean it up later, so yeah, you won't have to download the generated audio, you can send it immediately.

(i suggest combining bark voice cloning for the same voice as your RVC model, it yields highly impressive results)

**Comment by Ph0rk0z** [comment]
I will have to see how it keeps across sentences. That was my problem with bark. The first part was almost indistinguishable from the original speaker and then the next sentence would be an english lady or some dude. I do know that's how it goes.
