### ISSUE TITLE
[QUESTION] Keeps asking me to install MS BuildTools

### ISSUE THREAD

**Issue by NoMansPC** [gitmylo/audio-webui#98]
I already have it installed, though in another drive. Does audio web ui have to installed in the same drive as MS Buildtools to make it work?

**Comment by gitmylo** [comment]
as long as the build tools are on your path (aka, programs can find it) it works

**Comment by NoMansPC** [comment]
> You can add it manually to your path environment variable. https://stackoverflow.com/a/12608705 should tell you where the exe is located.

Okay, thanks! I also noticed that audio web ui completely makes A1111 and text webui unusable in my computer (probably because of the installation of different versions of the same programs). Should I have expected this to happen?

**Comment by gitmylo** [comment]
That is not supposed to happen, and i have not seen that happen before. Are you sure it was caused by audio-webui? It does not install anything new system wide, unless you specifically launched with the `--skip-venv` flag

**Comment by NoMansPC** [comment]
> That is not supposed to happen, and i have not seen that happen before. Are you sure it was caused by audio-webui? It does not install anything new system wide, unless you specifically launched with the `--skip-venv` flag

Maybe I did something that caused that. Before posting here I did try moving the folder to the drive where the MS Buildtools were (it didn't solve the initial problem I was having). After that I noticed that A1111 and text webui weren't working anymore. I'll try installing audio webui later since I don't have to reinstall everything again.

**Comment by gitmylo** [comment]
I'm closing inactive issues related to bugs with only 1 reporter, if you're still having this issue, reopen the issue.

**Comment by harunimsirovic** [comment]
Im stuck at the same issue, tried the SO link above as well

**Comment by gitmylo** [comment]
> Im stuck at the same issue, tried the SO link above as well

what error do you get?

**Comment by harunimsirovic** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tts
ERROR: Could not build wheels for tts, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip



You need to have visual studio C++ build tools installed. https://visualstudio.microsoft.com/visual-cpp-build-tools/.
Please read the error above carefully.

But I have it installed

**Comment by harunimsirovic** [comment]
Well, rebooting fixed it..
